### ISSUE TITLE
[Doc] Fans

### ISSUE THREAD

**Issue by tomaae** [MUTEtheCyberwolf/VALVE-INDEX-DEV-Frunk-1.0#1]
Hi,
I'm quite interested in this project.
Could you please document which fans/fan assembly are you using with this project?

**Comment by MUTEtheCyberwolf** [comment]
The Fan Assembly is currently in development. A direct connection to the Eyetracking ESP's is possible. The Frunk was designed for two 30x30x7mm Fans that Pressfit into the Carrier Plate from the Inside. 

Those here will do the Trick. 

https://de.aliexpress.com/item/1005004661799681.html?spm=a2g0o.productlist.main.19.6f7b3e17HkXs6X&algo_pvid=b5094cbc-09c7-4a3e-a973-bf156b23f6db&aem_p4p_detail=202308111135571223155924241150004009309&algo_exp_id=b5094cbc-09c7-4a3e-a973-bf156b23f6db-9&pdp_npi=4%40dis%21EUR%215.63%213.49%21%21%216.05%21%21%40211b5dfd16917789571864278e08be%2112000030022630089%21sea%21DE%212478567367%21&curPageLogUid=AzOYK0PbCIOJ&search_p4p_id=202308111135571223155924241150004009309_2

**Comment by tomaae** [comment]
perfect, thanks. I still have time to cancel my noctua 40x40x10 fan order then. should have measured it, silly me.
being in development is fine, it will take a while to get all components I need anyway and in worst case can always just jury rig my own temporary controller and air duct.
I was also looking into xiao mount, wont it significantly cover fan exhaust? I may look into redesigning it once I get all components, I'm still waiting for IR V4 board. I will need to see how cables can be managed there first.

Btw, where did you get this right angle usb socket? that looks very clean.
![image](https://github.com/MUTEtheCyberwolf/VALVE-INDEX-DEV-Frunk-1.0/assets/23486452/6d0e618b-eb42-4b64-92a5-2bdce16d787f)

**Comment by MUTEtheCyberwolf** [comment]
The XIAO Mount was designed with reduced Sensor Occlusion in mind. The Final Eyetracking PCB will take care of that by moving them closer together.  A User on Discord already printed the XIAO design. It occludes the Airflow a little bit but that will be taken care of with the final Version. The Fans have enough Pressure to get the hot Air out tho.  Props to @Captaincat for the clean build.
![image](https://github.com/MUTEtheCyberwolf/VALVE-INDEX-DEV-Frunk-1.0/assets/98415183/8ed6ec05-feee-4ff2-96b7-7a1dd50c0d60)
The 90° Connector can be purchased from Amazon without any problems.
![image](https://github.com/MUTEtheCyberwolf/VALVE-INDEX-DEV-Frunk-1.0/assets/98415183/8a02ce60-5a4d-46ac-8490-41eb20b56579)

**Comment by tomaae** [comment]
oh yea, that looks really good. so one in github screenshot is something different, just looking similar. I will probably look into having those xiao board fully covered for both eastethic and component safety. that should be easy tho.
Maybe adding some dust filter behind those holes, so dust wont settle in when headset is left on the stand.
Thanks for all the sources, I'm going to order everything. And of course, thanks for excellent job on this project.

I got this hub btw: https://www.amazon.de/-/en/3-0-Hub-MacBook-Windows-Ultrabooks-Compatible/dp/B00Y211AFM
Small, cheap and good brand. I'm thinking about taking it apart and making custom cover for it to hide all connectors.

**Comment by MUTEtheCyberwolf** [comment]
That Hub should be fine. The Picture linked to the Github was a early version of the Frunk using the Old ESPCAM Modules which are currently obsolete. I prefer and highly recommend using the XIAOs with USB Serial instead of WIFI. You can add Dustfilters but make sure they are not too dense. The Hole size is actually increased to allow a better Airflow through the Frunk. That would result in lower fanspeeds/quieter Operations and also better Thermal Management. 

I would also recommend you to join the EyetrackVR Discord.

The Fans will be Documented when the Controller is officially out. Until then I would Close this Issue.
