### ISSUE TITLE
Questions about the PCB

### ISSUE THREAD

**Issue by Thelvaen** [MUTEtheCyberwolf/VALVE-INDEX-DEV-Frunk-1.0#2]
Hello,

First of all, many thanks for your project, it really goes in the right direction for that kind of accessories (Valve should have made the frunk with the screw inserts from the start I think).

I wanted to take a look at the PCB, sadly it's missing the pick'n'place file (CPL) that would be required to order it with component placed through JLCPCB.

You probably could just publish your EasyEDA project to oshwlab, so everything required to just "order" the PCB with "almost" everything on it from JLCPCB would be there.

Regards,
Thelvaen

**Comment by MUTEtheCyberwolf** [comment]
Can try to do that the upcoming days. I don't really recommend using the old PCB Design anymore since i had some issues with the HUB Controller on it. It "might" work flawlessley with the Project Babble Facial tracker but i haven't tested it yet.

**Comment by Thelvaen** [comment]
Having it on OSHWlab would allow people to fork it and try to improve it / or simplify it depending on their needs :)

**Comment by MUTEtheCyberwolf** [comment]
OSHWLAB Link has been added. The PCB Project is unlisted tho everyone can get the design files from there through the link in the Readme.
